version: 2
jobs:
  build:
    docker:
      - image: 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:play-app
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx4g
      TERM: dumb

    steps:
      - checkout

      # ... steps for building/testing app ...

      - setup_remote_docker:   # (2)
          docker_layer_caching: false # (3)

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # build and push Docker image
      - run:
          command: |
            for jar in stanford-english-corenlp-2018-02-27-models.jar stanford-english-kbp-corenlp-2018-02-27-models.jar ; do
              wget --no-clobber http://nlp.stanford.edu/software/$jar
              jar xf $jar
            done
            eval `aws ecr get-login --no-include-email --region $AWS_REGION`
            gradle distDocker

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gradle
            - stanford-english-corenlp-2018-02-27-models.jar
            - stanford-english-kbp-corenlp-2018-02-27-models.jar
          key: v1-dependencies-{{ checksum "build.gradle" }}

